name 'nagios_liatrio'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures nagios_liatrio'
long_description 'Installs/Configures nagios_liatrio'
version '0.1.0'
